[project]
name = "meta-scout-maverick"
version = "2025.04.07"
description = "AI Resource Program"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "huggingface-hub>=0.30.1",
    "llama-stack>=0.2.1",
    "torch>=2.6.0",
    "transformers>=4.51.0",
]
